name: base
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py310h06a4308_0
  - cffi=1.15.1=py310h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - conda=23.1.0=py310h06a4308_0
  - conda-content-trust=0.1.3=py310h06a4308_0
  - conda-package-handling=2.0.2=py310h06a4308_0
  - conda-package-streaming=0.7.0=py310h06a4308_0
  - cryptography=38.0.4=py310h9ce1e76_0
  - idna=3.4=py310h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1s=h7f8727e_0
  - pip=22.3.1=py310h06a4308_0
  - pluggy=1.0.0=py310h06a4308_1
  - pycosat=0.6.4=py310h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.9=h7a1cb2a_0
  - readline=8.2=h5eee18b_0
  - ruamel.yaml=0.17.21=py310h5eee18b_0
  - ruamel.yaml.clib=0.2.6=py310h5eee18b_1
  - setuptools=65.6.3=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.1=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - toolz=0.12.0=py310h06a4308_0
  - tqdm=4.64.1=py310h06a4308_0
  - tzdata=2022g=h04d1e81_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - zstandard=0.18.0=py310h5eee18b_0
  - pip:
      - annotated-types==0.7.0
      - anyio==4.4.0
      - appdirs==1.4.4
      - asgiref==3.6.0
      - async-timeout==4.0.2
      - attr==0.3.1
      - attrs==24.2.0
      - azure-core==1.26.3
      - azure-storage-blob==12.15.0
      - bcrypt==4.0.1
      - bleach==5.0.1
      - blessed==1.20.0
      - blinker==1.7.0
      - boto==2.49.0
      - boto3==1.34.154
      - botocore==1.34.154
      - boxing==0.1.4
      - cachetools==5.3.0
      - click==8.1.3
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.2.0
      - coreapi==2.3.3
      - coreschema==0.0.4
      - cycler==0.12.1
      - defusedxml==0.7.1
      - deprecated==1.2.14
      - distro==1.8.0
      - django==3.2.25
      - django-annoying==0.10.6
      - django-cors-headers==3.6.0
      - django-csp==3.7
      - django-debug-toolbar==3.2.1
      - django-environ==0.10.0
      - django-extensions==3.1.0
      - django-filter==2.4.0
      - django-model-utils==4.1.1
      - django-ranged-fileresponse==0.1.2
      - django-rest-swagger==2.2.0
      - django-rq==2.5.1
      - django-storages==1.12.3
      - django-user-agents==0.4.0
      - djangorestframework==3.13.1
      - docker==6.0.1
      - docker-compose==1.29.2
      - dockerpty==0.4.1
      - docopt==0.6.2
      - drf-dynamic-fields==0.3.0
      - drf-flex-fields==0.9.5
      - drf-generators==0.3.0
      - drf-yasg==1.20.0
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.2
      - expiringdict==1.2.2
      - filelock==3.13.1
      - flask==2.3.3
      - flatbuffers==23.5.26
      - fonttools==4.49.0
      - fsspec==2024.2.0
      - google-api-core==2.19.1
      - google-auth==2.32.0
      - google-cloud-appengine-logging==1.1.0
      - google-cloud-audit-log==0.2.0
      - google-cloud-core==2.3.2
      - google-cloud-logging==3.11.0
      - google-cloud-storage==2.18.0
      - google-crc32c==1.5.0
      - google-resumable-media==2.7.1
      - googleapis-common-protos==1.56.4
      - gpustat==1.1
      - grpc-google-iam-v1==0.13.1
      - grpcio==1.53.0
      - grpcio-status==1.48.2
      - gunicorn==20.1.0
      - h11==0.14.0
      - htmlmin==0.1.12
      - httpcore==1.0.5
      - httpx==0.27.0
      - humanfriendly==10.0
      - humansignal-drf-yasg==1.21.9
      - ijson==3.3.0
      - importlib-metadata==8.0.0
      - inflection==0.5.1
      - isodate==0.6.1
      - itsdangerous==2.1.2
      - itypes==1.2.0
      - jinja2==3.1.3
      - jmespath==0.10.0
      - joblib==1.2.0
      - jsonschema==3.2.0
      - kiwisolver==1.4.5
      - label-studio-converter==0.0.50
      - label-studio-ml==2.0.1.dev0
      - label-studio-sdk==1.0.2
      - label-studio-tools==0.0.3
      - launchdarkly-server-sdk==8.2.1
      - lockfile==0.12.2
      - lxml==4.9.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.2
      - matplotlib==3.8.3
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.2.1
      - nltk==3.6.7
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==11.525.112
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - onnx==1.12.0
      - onnx-simplifier==0.4.8
      - onnxruntime==1.12.0
      - onnxruntime-gpu==1.16.3
      - onnxsim==0.4.36
      - openai==1.39.0
      - openapi-codec==1.3.2
      - opencv-python==4.9.0.80
      - openpyxl==3.1.4
      - opentelemetry-api==1.26.0
      - ordered-set==4.0.2
      - outcome==1.3.0.post0
      - packaging==23.0
      - pandas==1.3.5
      - paramiko==3.1.0
      - pillow==10.4.0
      - proto-plus==1.24.0
      - protobuf==3.20.3
      - psutil==5.9.4
      - psycopg2==2.9.5
      - psycopg2-binary==2.9.9
      - py-cpuinfo==9.0.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pygments==2.17.2
      - pynacl==1.5.0
      - pyparsing==3.1.1
      - pyrfc3339==1.1
      - pyrsistent==0.19.3
      - python-dateutil==2.8.1
      - python-dotenv==0.21.1
      - python-json-logger==2.0.4
      - pytz==2022.7.1
      - pyyaml==6.0.1
      - redis==3.5.3
      - regex==2023.3.23
      - requests==2.32.3
      - requests-mock==1.12.1
      - rich==13.7.0
      - rq==1.10.1
      - rsa==4.9
      - rules==2.2
      - s3transfer==0.10.2
      - scipy==1.12.0
      - seaborn==0.13.0
      - selenium==4.23.1
      - semver==3.0.2
      - sentry-sdk==1.18.0
      - simplejson==3.18.4
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - sqlparse==0.4.3
      - sympy==1.12
      - texttable==1.6.7
      - thop==0.1.1-2209072238
      - torch==2.2.1
      - torchvision==0.17.1
      - trio==0.26.2
      - trio-websocket==0.11.1
      - triton==2.2.0
      - typing-extensions==4.10.0
      - ua-parser==0.16.1
      - ujson==5.10.0
      - ultralytics==8.2.38
      - ultralytics-thop==2.0.0
      - uritemplate==4.1.1
      - urllib3==1.26.19
      - user-agents==2.2.0
      - wcwidth==0.2.6
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.1
      - wheel==0.40.0
      - wrapt==1.16.0
      - wsproto==1.2.0
      - xmljson==0.2.1
      - zipp==3.19.2
prefix: /root/miniconda3
